---
apiVersion: v1
kind: Service
metadata:
  name: simple-go-service-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: simple-go-service
